"""add cascade delete to task responses and attachments

Revision ID: 676cd0c24fc3
Revises: fe264b2e9634
Create Date: 2025-12-22 13:33:46.892240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676cd0c24fc3'
down_revision: Union[str, Sequence[str], None] = 'fe264b2e9634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('task_attachments_task_id_fkey'), 'task_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'task_attachments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_responses_task_id_fkey'), 'task_responses', type_='foreignkey')
    op.create_foreign_key(None, 'task_responses', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_responses', type_='foreignkey')
    op.create_foreign_key(op.f('task_responses_task_id_fkey'), 'task_responses', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_attachments', type_='foreignkey')
    op.create_foreign_key(op.f('task_attachments_task_id_fkey'), 'task_attachments', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
