"""add_fields_to_task_model

Revision ID: fe264b2e9634
Revises: 734285762369
Create Date: 2025-12-21 18:43:45.710983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe264b2e9634'
down_revision: Union[str, Sequence[str], None] = '734285762369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('repeats', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('file_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'file_link')
    op.drop_column('tasks', 'repeats')
    op.drop_column('tasks', 'deadline')
    op.drop_column('tasks', 'difficulty')
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###
